### ISSUE TITLE
[Android] Todo Repository 구현

### ISSUE THREAD

**Issue by banjjak2** [ku-kim/todo-list#49]
## 기능 요청사항

- Todo 관련 레포지토리 기능 구현

## 요청 세부사항

- [x] Todo 모델 작성
- [x] Retrofit을 이용한 통신
- [x] 추가/삭제/수정 구현
- [x] UI 완료 전 테스트 진행
